name: "Twitter Behavior (Logged In)"

on:
  push:
  pull_request:
  schedule:
    - cron: "14 16 * * *"

jobs:
  twitter_logged_in_test:
    environment: DigitalOcean
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: prewk/s3-cp-action@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          SOURCE: ${{ secrets.PROFILE_URL }}
          DEST: "./profile.tar.gz"

      - name: install requirements
        run: yarn install

      - name: build behaviors
        run: yarn run build

      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: test/test.env

      - name: get browsertrix image
        run: docker pull $BROWSERTRIX_IMAGE

      - name: run crawl
        run: docker run -v $PWD/dist/behaviors.js:/app/node_modules/browsertrix-behaviors/dist/behaviors.js -v $PWD/profile.tar.gz:/profile.tar.gz $BROWSERTRIX_IMAGE crawl --url https://twitter.com/CaptureSample --limit 1 --logging behaviors --profile /profile.tar.gz > ./log

      - name: cat log
        run: cat ./log

      - uses: sergeysova/jq-action@v2
        name: compare crawl log to expected
        with:
          cmd: >
            cat log
            | jq -Rr -c 'fromjson? | .details | select(type == "object") | {msg,state} | select(.msg != null) | select(.msg | contains("?cxt") | not)'
            | diff - ./test/expected-twitter-logged-in.log
